### ISSUE TITLE
Broken build with postgresql 9.2

### ISSUE THREAD

**Issue by remicollet** [m6w6/ext-pq#18]
```
/builddir/build/BUILD/php-pecl-pq-1.1.0/NTS/src/php_pqres.c: In function 'php_pqres_object_read_diag':
/builddir/build/BUILD/php-pecl-pq-1.1.0/NTS/src/php_pqres.c:531:5: error: 'PG_DIAG_SCHEMA_NAME' undeclared (first use in this function)
    {PG_DIAG_SCHEMA_NAME,  "schema_name"},
     ^
/builddir/build/BUILD/php-pecl-pq-1.1.0/NTS/src/php_pqres.c:531:5: note: each undeclared identifier is reported only once for each function it appears in
/builddir/build/BUILD/php-pecl-pq-1.1.0/NTS/src/php_pqres.c:532:5: error: 'PG_DIAG_TABLE_NAME' undeclared (first use in this function)
    {PG_DIAG_TABLE_NAME,  "table_name"},
     ^
/builddir/build/BUILD/php-pecl-pq-1.1.0/NTS/src/php_pqres.c:533:5: error: 'PG_DIAG_COLUMN_NAME' undeclared (first use in this function)
    {PG_DIAG_COLUMN_NAME,  "column_name"},
     ^
/builddir/build/BUILD/php-pecl-pq-1.1.0/NTS/src/php_pqres.c:534:5: error: 'PG_DIAG_DATATYPE_NAME' undeclared (first use in this function)
    {PG_DIAG_DATATYPE_NAME,  "datatype_name"},
     ^
/builddir/build/BUILD/php-pecl-pq-1.1.0/NTS/src/php_pqres.c:535:5: error: 'PG_DIAG_CONSTRAINT_NAME' undeclared (first use in this function)
    {PG_DIAG_CONSTRAINT_NAME, "constraint_name"},
     ^

```

**Comment by m6w6** [comment]
Thanks (again)!

Unfortunately, travis does not support different package versions in the build matrix ;-/

Fixed in https://github.com/m6w6/ext-pq/commit/ff4439a509c64757948265ff83956bccef03c06e
